// src/js/constants/action-types.js

export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const ARTICLES_FETCH_SUCCEEDED = "ARTICLES_FETCH_SUCCEEDED";
export const ARTICLES_FETCH_ERROR = "ARTICLES_FETCH_ERROR";

export const FETCH_USERS = "FETCH_USERS";
export const USERS_FETCH_SUCCEEDED = "USERS_FETCH_SUCCEEDED";
export const USERS_FETCH_ERROR = "USERS_FETCH_ERROR";

export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const ARTICLE_FETCH_SUCCEEDED = "FETCH_ARTICLE_SUCCEEDED";
export const ARTICLE_FETCH_ERROR = "FETCH_ARTICLE_ERROR";

export const FETCH_ARTICLES_SEARCH = "FETCH_ARTICLE_SEARCH";
export const SEARCH_ARTICLES_FETCH_SUCCEEDED = "FETCH_ARTICLES_SEARCH_SUCCEEDED";
export const SEARCH_ARTICLES_FETCH_ERROR = "FETCH_ARTICLES_SEARCH_ERROR";

export const LOADING = "LOADING";

export const FETCH_TOKEN = "FETCH_TOKEN";
export const TOKEN_FETCH_SUCCEEDED = "TOKEN_FETCH_SUCCEEDED";
export const TOKEN_FETCH_ERROR = "TOKEN_FETCH_ERROR";

export const FETCH_USER = "FETCH_USER";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";